server:
  port: 8888
  
logging:
  level:
    com.dcl.dao: debug
    
spring:
  mvc:
    servlet:
      load-on-startup: 1
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///shiro?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  cache:
    type: ehcache
    ehcache:
      config: classpath:cache/ehcache.xml
    